ESTADO_AGUARDANDO = "AGUARDANDO"
ESTADO_DIGITANDO = "DIGITANDO"
ESTADO_VALIDANDO = "VALIDANDO"
ESTADO_ACESSO_OK = "ACESSO_OK"
ESTADO_BLOQUEADO = "BLOQUEADO"
ESTADO_LOCKOUT = "LOCKOUT"

# Mantido fixo para simulacao.
PIN_CADASTRADO = "1234"
TAMANHO_PIN = 4
MAX_TENTATIVAS = 3
TEMPO_LOCKOUT = 10

# Pinos validados no diagrama atual.
BUZZER_PIN = 13
LED_VERMELHO_PIN = 27
ATUADOR_FECHADURA_PIN = 26
LED_VERDE_PIN = 25
LED_AMARELO_PIN = 32
BOTAO_TESTE_PIN = 33
# Reset por software no GPIO35.
BOTAO_RESET_PIN = 35
POT_VOLUME_PIN = 34
LCD_SDA_PIN = 21
LCD_SCL_PIN = 22
SERVO_PIN = 14

SERVO_DUTY_FECHADO = 3277
SERVO_DUTY_ABERTO = 6554
SERVO_FREQ_HZ = 50

BUZZER_FREQ_HZ = 2000
BUZZER_DUTY_MAX = 32768
ADC_VALOR_MAX = 4095
BOTAO_SOLTO = 1
BOTAO_PRESSIONADO = 0

INTERVALO_PISCA_MS = 300
DURACAO_ACESSO_OK_MS = 3000
DURACAO_BLOQUEIO_MS = 800
INTERVALO_LOOP_MS = 50
STDIN_POLL_TIMEOUT_MS = 0
DEBOUNCE_BOTAO_MS = 50
INTERVALO_LCD_LOCKOUT_MS = 1000
INTERVALO_LOG_LOCKOUT_MS = 1000
MILLIS_POR_SEGUNDO = 1000
ARREDONDAMENTO_SEGUNDO_MS = 999

AUTOTESTE_LED_MS = 300
AUTOTESTE_ATUADOR_MS = 500
AUTOTESTE_SERVO_MS = 700
AUTOTESTE_BUZZER_MS = 400
AUTOTESTE_OK_MS = 800

LCD_I2C_ID = 0
LCD_I2C_FREQ = 400000
LCD_I2C_ADDR = 0x27
ADC_ATENUACAO = 3

DEBUG_ATIVO_INICIAL = True
COMANDOS_DEBUG_HABILITADOS = True
MASCARAR_PIN_NO_LOG = True

MSG_BOOT = "VaultSign iniciado."
PIN_MASK_CHAR = "*"
EMPTY_TEXT = ""
PIN_LOG_EMPTY = "-"

LCD_TITULO = "VaultSign"
LCD_AGUARDANDO = "Aguardando PIN"
LCD_DIGITE_PIN = "Digite o PIN"
LCD_VALIDANDO = "Validando..."
LCD_ACESSO_OK = "ACESSO OK"
LCD_BEM_VINDO = "Bem-vindo"
LCD_PIN_INVALIDO = "PIN INVALIDO"
LCD_TENTATIVAS_FORMAT = "Tent {}/{}"
LCD_BLOQUEADO = "BLOQUEADO"
LCD_AGUARDE_FORMAT = "Aguarde {}s"
LCD_AUTOTESTE = "AUTO-TESTE"
LCD_LED_AMARELO = "LED Amarelo"
LCD_LED_VERMELHO = "LED Vermelho"
LCD_LED_VERDE = "LED Verde"
LCD_FECHADURA_LOCK = "Fechadura+LOCK"
LCD_SERVO = "Servo"
LCD_BUZZER_POT = "Buzzer/Pot"
LCD_AUTOTESTE_OK = "OK!"

DEVICE_LED_VERDE = "led_verde"
DEVICE_LED_VERMELHO = "led_vermelho"
DEVICE_LED_AMARELO = "led_amarelo"
DEVICE_ATUADOR_FECHADURA = "atuador_fechadura"
DEVICE_BUZZER = "buzzer"
DEVICE_SERVO = "servo"
DEVICE_BOTAO_TESTE = "botao_teste"
DEVICE_BOTAO_RESET = "botao_reset"
DEVICE_POT_VOLUME = "pot_volume"
DEVICE_LCD = "lcd"

ACTION_ON = "ligar"
ACTION_OFF = "desligar"
ACTION_TOGGLE = "alternar"
ACTION_READ = "ler"
ACTION_WRITE = "escrever"
ACTION_OPEN = "abrir"
ACTION_CLOSE = "fechar"

DEBUG_CMD_STATUS = "?"
DEBUG_CMD_STATUS_ALT = "s"
DEBUG_CMD_TOGGLE = "d"
DEBUG_CMD_CLEAR = "c"
DEBUG_CMD_UNLOCK = "u"
DEBUG_CMD_HELP = "h"

CHAR_CR = "\r"
CHAR_LF = "\n"
CHAR_SPACE = " "
CHAR_TAB = "\t"
CARACTERES_IGNORADOS = (CHAR_CR, CHAR_LF, CHAR_SPACE, CHAR_TAB)

ENTRADA_IGNORADA = 1
ENTRADA_INVALIDA = 2
ENTRADA_PARCIAL = 3
ENTRADA_COMPLETA = 4
ENTRADA_OVERFLOW = 5
